---

spring:
    h2.console.enabled=true
    datasource.url=jdbc:h2:mem:ticketing;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    datasource.driverClassName=org.h2.Driver
    datasource.username=sa
    datasource.password=
    jpa.database-platform=org.hibernate.dialect.H2Dialect

logging:
     level.org.hibernate.SQL=debug

highest:
    level=4
db:
    schema.name=ticketing