

-- -----------------------------------------------------
-- Table LEVEL
-- -----------------------------------------------------
DROP TABLE IF EXISTS LEVEL ;

CREATE TABLE IF NOT EXISTS LEVEL (
  ID INT NOT NULL,
  LEVEL_NAME VARCHAR(100) NULL,
  PRICE DECIMAL(10) NULL,
  NUMBER_OF_ROW INT NULL,
  SEATS_PER_ROW INT NULL,
  PRIMARY KEY (ID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table SEAT
-- -----------------------------------------------------
DROP TABLE IF EXISTS SEAT ;

CREATE TABLE IF NOT EXISTS SEAT (
  ID INT NOT NULL,
  SEAT_NUMBER INT NULL,
  ROW_NUMBER INT NOT NULL,
  LEVEL INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_LEVEL
    FOREIGN KEY (LEVEL)
    REFERENCES LEVEL (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX FK_LEVEL_idx ON SEAT (LEVEL ASC);


-- -----------------------------------------------------
-- Table CUSTOMER
-- -----------------------------------------------------
DROP TABLE IF EXISTS CUSTOMER ;

CREATE TABLE IF NOT EXISTS CUSTOMER (
  ID INT NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID))
ENGINE = InnoDB;

CREATE UNIQUE INDEX EMAIL_UNIQUE ON CUSTOMER (EMAIL ASC);


-- -----------------------------------------------------
-- Table STATUS
-- -----------------------------------------------------
DROP TABLE IF EXISTS STATUS ;

CREATE TABLE IF NOT EXISTS STATUS (
  ID INT NOT NULL,
  STATUS_DESC VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table RESERVATION
-- -----------------------------------------------------
DROP TABLE IF EXISTS RESERVATION ;

CREATE TABLE IF NOT EXISTS RESERVATION (
  ID INT NOT NULL AUTO_INCREMENT,
  STATUS INT NULL,
  LEVEL INT NULL,
  CUSTOMER_ID INT NOT NULL,
  CONFIRMATION_CODE VARCHAR(36) NOT NULL,
  NUMBER_OF_SEATS INT NULL,
  HOLD_TIME DATETIME NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_RESERVATION_STATUS
    FOREIGN KEY (STATUS)
    REFERENCES STATUS (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_RESERVATION_LEVEL
    FOREIGN KEY (LEVEL)
    REFERENCES LEVEL (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX FK_STATUS_idx ON RESERVATION (STATUS ASC);

CREATE INDEX FK_LEVEL_RESER_idx ON RESERVATION (LEVEL ASC);

CREATE INDEX FK_CUSTOMER_idx ON RESERVATION (CUSTOMER_ID ASC);


-- -----------------------------------------------------
-- Table SEAT_HOLD
-- -----------------------------------------------------
DROP TABLE IF EXISTS SEAT_HOLD ;

CREATE TABLE IF NOT EXISTS SEAT_HOLD (
  ID INT NOT NULL AUTO_INCREMENT,
  SEAT_ID INT NOT NULL,
  RESERVATION_ID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_SEAT_ID
    FOREIGN KEY (SEAT_ID)
    REFERENCES SEAT (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_RESERVATION_ID
    FOREIGN KEY (RESERVATION_ID)
    REFERENCES RESERVATION (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX FK_RESERVATION_ID_idx ON SEAT_HOLD (RESERVATION_ID ASC);

CREATE INDEX FK_SEAT_ID_idx ON SEAT_HOLD (SEAT_ID ASC);
